pickrr/pickrr/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'pickrr.views.home', name='home'),
    url(r'^',include('pickup.urls',namespace='pickup')),
    url(r'^faqs/$', TemplateView.as_view(template_name='staticpages/faqs.html'), name='faq'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^order/',include('orders.urls',namespace='orders')),
    url(r'^tracking/',include('track.urls',namespace='track')),
    url(r'^api/',include('pickrr_common_api.urls',namespace='pickrr_common_api')),
    url(r'^price-calculator/',include('externalpriceapi.urls',namespace='externalpriceapi')),
    #url(r'^vendor-api/',include('vendorapi.urls',namespace='vendorapi')),
    url(r'^location/',include('locations.urls',namespace='locations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^weshyp/admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^weshyp/admin/', include(admin.site.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

pickrr/pickup/urls.py
from django.conf.urls import patterns, url
from pickup import views

urlpatterns = patterns('',
    url(r'^$',views.home_pickrr,name='home_pickrr'),
    url(r'^select-service/$',views.select_service,name='select_service'),
    url(r'^(?P<from_location_id>.+)/(?P<to_location_id>.+)/show-service-api/$',views.show_service_api,name='show_service_api'),
)

pickrr/track/urls.py
from django.conf.urls import patterns, url
from track import views

urlpatterns = patterns('',
	url(r'^$',views.search_tracking,name='search_tracking'),
    url(r'^(?P<key>.+)/(?P<track_id>.+)/$',views.show_tracking,name='show_tracking'),
    url(r'^(?P<tracking_id>.+)/mobile/api$',views.tracking_api,name='tracking_api'),
)

pickrr/pickup/models.py
from django.db import models

# Create your models here.

pickrr/pickup/forms.py
from django import forms
from locations.models import City
from products.models import Product
import random

class SchedulePickupForm(forms.Form):
    from_location = forms.ChoiceField(label="From Location",required=True,
        widget=forms.Select(attrs={'class': 'pickrr-drop'}))
    to_location = forms.ChoiceField(label="To Location",required=True,
        widget=forms.Select(attrs={'class': 'pickrr-drop'}))
    #product = forms.ChoiceField(label="Enter items to be shipped",required=True)

    def __init__(self, *args, **kwargs):
        super(SchedulePickupForm, self).__init__(*args, **kwargs)
        #For dynamically changing the from city values as per our expansion plans
        self.fields['from_location'].choices = [ (from_city.id, str(from_city.name)) for from_city in sorted(City.objects.filter(from_service=True),key=lambda x: random.random())]
        #For dynamically changing the to city
        self.fields['to_location'].choices = [ (to_city.id, str(to_city.name)) for to_city in sorted(City.objects.filter(to_service=True),key=lambda x: random.random())]
        #self.fields['product'].choices = [ (prod.id, str(prod.name)) for prod in Product.objects.all()]

pickrr/pickup/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect, get_list_or_404, Http404
from django.core.urlresolvers import reverse
from django.template import Context, RequestContext
from django.core.context_processors import csrf
from pricingmodel.models import PickrrZone
from products.models import Product
from locations.models import *
from pickup.forms import SchedulePickupForm
from users.models import MainUser
from helpers.helpers import JsonResponse

def get_value_from_request(get_array,request):
    value_array = []
    for value in get_array:
        get_id = request.session.get(value,False)
        if not get_id:
            raise Http404
        else:
            #del request.session[value]
            value_array.append(get_id)
    return value_array

#schedule pickup checkout flow starts from here
def home_pickrr(request):
    """
    #SCript for adding archies data to their account
    from track.models import Status
    user_obj = get_object_or_404(MainUser,email='archies@pickrr.com')
    track_arch = get_list_or_404(Status,tracking_id__icontains='PICK')
    for track in track_arch:
        track.order.user = user_obj
        track.order.save()
    from track.models import Status
    track_list = Status.objects.all()
    from users.views import key_gen
    for track in track_list:
        if not track.key:
            track.key=key_gen(track.pk)
            track.save()
    from helpers.helpers import generate_mobile_api_token, filter_or_none
    user_list = filter_or_none(MainUser,is_guest=False)
    print user_list
    for user_obj in user_list:
        if not user_obj.mobile_token:
            auth_token = str(generate_mobile_api_token(user_obj.pk))+ str(user_obj.pk)
            user_obj.mobile_token = auth_token
            user_obj.save()
    """
    pickupform = SchedulePickupForm()
    if request.method=='POST':
        pickupform = SchedulePickupForm(request.POST)
        if pickupform.is_valid():
            from_location_id = pickupform.cleaned_data['from_location']
            to_location_id = pickupform.cleaned_data['to_location']
            #product_id = pickupform.cleaned_data['product']
            request.session['from_location_id'] = from_location_id
            request.session['to_location_id'] = to_location_id
            #request.session['product_id'] = product_id
            return redirect('pickup:select_service')
    return render_to_response('pickup/home_pickrr.html',
                            {'pickupform':pickupform},
                            context_instance=RequestContext(request))

def select_service(request):
    if request.method=='POST':
        service_id = request.POST.get('service_type')
        if not service_id:
            raise Http404
        #print request.session.get('from_location_id',False)
        request.session['service_id'] = service_id
        if request.user.is_authenticated():
            user = get_object_or_404(MainUser,user=request.user)
            request.session['user_id'] = user.pk
            return redirect('orders:checkout_pickup_address')
        else:
            return redirect('orders:checkout_flow')
    request_parameter_array = ['from_location_id','to_location_id']
    id_array = get_value_from_request(request_parameter_array,request)
    from_city = get_object_or_404(City,pk=id_array[0])
    to_city = get_object_or_404(City,pk=id_array[1])
    #product = get_object_or_404(Product,pk=id_array[2])
    #Define Intracity:
    if to_city.from_service and to_city.to_service:
        service_type = 'Intracity'
        zone = get_object_or_404(PickrrZone,zone_name='Intracity')
        services = zone.pickrrservices_set.all()
    #Intercity
    else:
        service_type = 'Intercity'
        zone = to_city.pickrr_zone
        services = zone.pickrrservices_set.all()
    return render_to_response('pickup/select_service.html',
                            {'from_city':from_city,
                            'to_city':to_city,
                            #'product':product,
                            'services':services,
                            'service_type':service_type},
                            context_instance=RequestContext(request))

def show_service_api(request,from_location_id,to_location_id):
    from_city = get_object_or_404(City,pk=int(from_location_id))
    to_city = get_object_or_404(City,pk=int(to_location_id))
    #Define Intracity:
    if to_city.from_service and to_city.to_service:
        service_type = 'Intracity'
        rush_timeline = 'within 90 min'
        rush_base_fare = 150
        rush_base_weight = 500
        rush_add_fare = 100
        premium_timeline = 'within 4-5 hrs'
        premium_base_fare = 80
        premium_base_weight = 500
        premium_add_fare = 80
        standard_timeline = 'within 24 hrs'
        standard_base_fare = 59
        standard_base_weight = 500
        standard_add_fare = 59
    #Intercity
    else:
        service_type = 'Intercity'
        zone = to_city.pickrr_zone
        services = zone.pickrrservices_set.all()
        for service in services:
            if service.service_name == 'Rush':
                rush_base_fare = service.base_price
                rush_add_fare = service.add_price
            elif service.service_name == 'Premium':
                premium_base_fare = service.base_price
                premium_add_fare = service.add_price
            else:
                standard_base_fare = service.base_price
                standard_add_fare = service.add_price
        rush_timeline = 'within 1-2 days'
        #rush_base_fare = 180
        rush_base_weight = 500
        #rush_add_fare = 120
        premium_timeline = 'within 2-4 days'
        #premium_base_fare = 120
        premium_base_weight = 500
        #premium_add_fare = 60
        standard_timeline = 'within 4-6 days'
        #standard_base_fare = 65
        standard_base_weight = 500
        #standard_add_fare = 60
    response_data = {}
    response_data['rush_timeline'] = rush_timeline
    response_data['rush_base_fare'] = rush_base_fare
    response_data['rush_base_weight'] = rush_base_weight
    response_data['rush_add_fare'] = rush_add_fare
    response_data['premium_timeline'] = premium_timeline
    response_data['premium_base_fare'] = premium_base_fare
    response_data['premium_base_weight'] = premium_base_weight
    response_data['premium_add_fare'] = premium_add_fare
    response_data['standard_timeline'] = standard_timeline
    response_data['standard_base_fare'] = standard_base_fare
    response_data['standard_base_weight'] = standard_base_weight
    response_data['standard_add_fare'] = standard_add_fare
    return JsonResponse(response_data)

pickrr/pickup/templates/pickup/home_pickrr.html
{% extends "__base.html" %}
{% block stylesheets %}
{% load static %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "icon/flaticon.css" %}">
{% endblock stylesheets %}
{% block body %}
<section id="landing">
  <div class="content-holder">
    <div class="container-fluid">
      <div class="row">
      <div class="col-md-5" id="pickrr-heading">
          <div class="trend-heading">
            <img src="{% static "img/logo.png" %}">
            <h2>Pick, Pack and Deliver !</h2>
            <h4>
              Now schedule a pickup  via call/whatsapp/android           
            </h4>
            <span class="com-span"><i class="mdi-communication-call mat-icon"></i> + 91-97-11-031164</span>
              <a href="tel:+91-97-11-031164" class="btn btn-default btn-com "><i class="mdi-communication-call mat-icon"></i> +91-97-11-031164</a>
            <a href="https://play.google.com/store/apps/details?id=app.www.pickrr.com.pickrr" style="padding-left:1em;">
              <img alt="Get it on Google Play"
                  src="https://developer.android.com/images/brand/en_generic_rgb_wo_45.png" />
            </a>
          </div>
        </div>
        <div class="col-md-7" data-position="side" id="pickrr-panel">
          <div class="panel panel-main panel-ajax shadow-z-2">
            <div class="panel-heading">
              <h3 class="panel-title">Tell us about your Shipment</h3>
            </div>
            <div class="panel-body">
              {% load widget_tweaks %}
              <form action="{% url 'pickup:home_pickrr' %}" class="form-horizontal form-ajax" method="post">{% csrf_token %}
                {% for field in pickupform %}
                {% if field.errors %}
                <div class="form-group has-error">
                  <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-8">
                    {{ field| add_class:"form-control" }}
                    <span class="help-block">
                      {% for error in  field.errors %}{{ error }}{% endfor %}
                    </span>
                  </div>
                </div>
                {% else %}
                <div class="form-group">
                  <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                  <div class="col-sm-8">
                    {{ field| add_class:"form-control" }}
                    {% if field.help_text %}
                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                  </div>
                </div>
                {% endif %}
                {% endfor %}
                <div class="form-group">
                  <div class="col-sm-offset-4 col-sm-8">
                    <button type="submit" class="btn btn-primary btn-raised">Schedule a Pickup <i class="mdi-navigation-chevron-right mat-icon"></i></button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="more-trig" data-target="#how-work">
    <h3>Know How ?</h3>
    <i class="mdi-navigation-expand-more mat-icon"></i>
  </div>
</section>
<section id="how-work">
  <div class="content-holder">
    <div class="pickrr-holder">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12 pickrr-tell">
            <h2>What you have to do !</h2>
            <div class="pickrr-sub shadow-z-1">
              <i class="flaticon-delivery37 flaticon"></i>
              <h4>Schedule</h4>
              <p>
                Schedule a hassle free Pickup in just few clicks through our website or via WhatsApp
              </p>
            </div>
          </div>
          <div class="col-md-12">
            <div class="separator"></div>
          </div>
          <div class="pickrr-tell">
            <h2>What we will do !</h2>
            <div class="col-md-4">
              <div class="pickrr-sub shadow-z-1">
                <i class="flaticon-cape1 flaticon"></i>
                <h4>Pick</h4>
                <p>
                  Your Pickrr will be at your doorsteps in just 60 minutes or as per your convenience.
                </p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="pickrr-sub shadow-z-1">
                <i class="flaticon-cardboard12 flaticon"></i>
                <h4>Pack</h4>
                <p>
                  Parcel will be packed by your Pickrr using the best-in-class material for free.
                </p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="pickrr-sub shadow-z-1">
                <i class="flaticon-flying flaticon"></i>
                <h4>Deliver</h4>
                <p>
                  Your Pickrr will ensure the delivery of parcel using the most efficient shipping mode.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</section>

{% endblock body %}

pickrr/pickup/templates/pickup/select_service.html
<div class="panel-heading">
    <h3 class="panel-title">Shipping Summary</h3>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="loc-card shadow-z-1 col-sm-4">
                <i class="mdi-maps-my-location mat-icon"></i>
                {{ from_city.name }}
            </div>
            <div class="col-sm-4 hidden-xs">
                <hr>
                <i class="mdi-device-airplanemode-on"></i>
            </div>
            <div class="loc-card shadow-z-1 col-sm-4">
                <i class="mdi-maps-pin-drop mat-icon"></i>
                {{to_city.name}}
            </div>
        </div>
    </div>
    <h3>Choose Delivery Option</h3>
    <br>
    <form class="form-horizontal form-ajax" method="POST" action="{% url 'pickup:select_service' %}">
        {% csrf_token %}
        {% if service_type == "Intracity" %}
        {% for service in services %}
        <div class="radio radio-success {% if service.service_name == 'Rush'  %}radio-rush{% endif %}">
            <label>
                <input type="radio" name="service_type" value="{{ service.pk }}" {% if service.service_name == 'Rush'  %}checked{% endif %}>
                <span class="circle"></span>
                <span class="check"></span>
                <div class="service-card">
                    <strong>{{ service.service_name }}</strong> 
                    <p class="main-pricing">- Rs. {{service.base_price}} for {{service.base_weight}} Kg</p>
                    <p class="pricing">
                        <i>Rs {{service.add_price}} per extra {{service.base_weight}} Kg</i>
                    </p>
                </div>
            </label>
            <div class="time-to">
                <i class="mdi-action-schedule mat-icon"></i>
                {% if service.service_name == 'Rush'  %}
                    Within {{service.max_service_duration}} minutes
                {% endif %}
                {% if service.service_name == 'Premium' %}
                    Within {{service.min_service_duration}} - {{service.max_service_duration}} hours
                {% endif %}
                {% if service.service_name == 'Standard' %}
                    Within {{service.max_service_duration}} hours
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% else %}
        {% for service in services %}
        <div class="radio radio-success">
             <label>
                <input type="radio" name="service_type" value="{{ service.pk }}" {% if service.service_name == 'Rush'  %}checked{% endif %}>
                <span class="circle"></span>
                <span class="check"></span>
                <div class="service-card">
                    <strong>{{ service.service_name }}</strong> 
                    <p class="main-pricing">- Rs. {{service.base_price}} for {{service.base_weight}} Kg</p>
                    <p class="pricing">
                        <i>Rs {{service.add_price}} per extra {{service.base_weight}} Kg</i>
                    </p>
                </div>
            </label>
            <div class="time-to">
                <i class="mdi-action-schedule mat-icon"></i>
                {% if service.service_name == 'Rush'  %}
                    Within {{service.min_service_duration}} - {{service.max_service_duration}} Days
                {% endif %}
                {% if service.service_name == 'Premium' %}
                    Within {{service.min_service_duration}} - {{service.max_service_duration}} days
                {% endif %}
                {% if service.service_name == 'Standard' %}
                    Within {{service.min_service_duration}} - {{service.max_service_duration}} days
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-primary btn-raised">Proceed to Checkout</button>
    </form>
</div>