pickrr/orders/urls.py
from django.conf.urls import patterns, url
from orders import views

urlpatterns = patterns('',
    url(r'^checkout/$',views.checkout_flow,name='checkout_flow'),
    url(r'^checkout/pickup/address/$',views.checkout_pickup_address,name='checkout_pickup_address'),
    url(r'^checkout/delivery/address/$',views.checkout_delivery_address,name='checkout_delivery_address'),
    url(r'^checkout/login/$',views.checkout_login_user,name='checkout_login_user'),
    url(r'^checkout/register/$',views.checkout_register_user,name='checkout_register_user'),
    url(r'^order-placed/$',views.pickup_order_placed,name='pickup_order_placed'),
    url(r'^place-order-app/$',views.order_placing_api,name='order_placing_api'),
    url(r'^cancel-order/(?P<order_id>.+)/$',views.cancel_order,name='cancel_order'),
    url(r'^order-placing-api/$',views.order_placing_business_api,name='order_placing_business_api'),
    url(r'^upload-order-data-ops/$',views.order_data_upload_ops,name='order_data_upload_ops'),
    url(r'^bluedart-waybill-generate/(?P<order_id>.+)/$', views.bluedart_waybill_generate, name='bluedart_waybill_generate'),
    url(r'^(?P<user_id>.+)/(?P<auth_token>.+)/user-orders-list/api/$',views.user_orders_api,name='user_orders_api'),
)

pickrr/pickrr/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'pickrr.views.home', name='home'),
    url(r'^',include('pickup.urls',namespace='pickup')),
    url(r'^faqs/$', TemplateView.as_view(template_name='staticpages/faqs.html'), name='faq'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^order/',include('orders.urls',namespace='orders')),
    url(r'^tracking/',include('track.urls',namespace='track')),
    url(r'^api/',include('pickrr_common_api.urls',namespace='pickrr_common_api')),
    url(r'^price-calculator/',include('externalpriceapi.urls',namespace='externalpriceapi')),
    #url(r'^vendor-api/',include('vendorapi.urls',namespace='vendorapi')),
    url(r'^location/',include('locations.urls',namespace='locations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^weshyp/admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^weshyp/admin/', include(admin.site.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

pickrr/track/urls.py
from django.conf.urls import patterns, url
from track import views

urlpatterns = patterns('',
	url(r'^$',views.search_tracking,name='search_tracking'),
    url(r'^(?P<key>.+)/(?P<track_id>.+)/$',views.show_tracking,name='show_tracking'),
    url(r'^(?P<tracking_id>.+)/mobile/api$',views.tracking_api,name='tracking_api'),
)

pickrr/orders/models.py
from django.db import models

class Order(models.Model):
    #order_id += order.pk
    order_id = models.CharField(max_length=256)
    user = models.ForeignKey('users.MainUser')
    pickup_address = models.ForeignKey('users.PickupAddress')
    drop_address = models.ForeignKey('users.DeliveryAddress')
    service_used = models.ForeignKey('pricingmodel.PickrrServices',blank=True,null=True)
    placed_at = models.DateTimeField(auto_now_add=True)
    scheduled_for = models.DateTimeField(blank=True,null=True)
    placed_at.editable = True
    total_bill = models.FloatField(default=0)
    invoice_sent = models.BooleanField(default=False)
    assigned_to = models.ForeignKey('pickrrs.Pickrrs',blank=True,null=True)
    is_cod = models.BooleanField(default=False)
    cod_amount = models.FloatField(default=0)
    is_cancelled = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.order_id)

    class Meta:
        ordering = ['-placed_at']

class OrderItems(models.Model):
    order = models.ForeignKey('Order')
    product = models.ForeignKey('products.Product',blank=True,null=True)
    quantity = models.IntegerField(default=1)
    length = models.FloatField(default=0)
    breadth = models.FloatField(default=0)
    height = models.FloatField(default=0)
    weight = models.FloatField(default=0.5)
    item_bill = models.FloatField(default=0)

    def __unicode__(self):
        return self.order.user.email

    class Meta:
        ordering = ['-pk']

pickrr/users/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth import get_user_model
from helpers.helpers import validate_pincode, validate_phone_number,generate_mobile_api_token

#Most appropriate way of getting user as it considers the active user model for your project. Either from auth,allauth or custom user model
User = get_user_model()

class MainUser(models.Model):
    #username and password will be user field
    user = models.OneToOneField(User,blank=True,null=True)
    name = models.CharField(max_length=128,verbose_name="Full Name",blank=True,null=True)
    #Form validation check: registered user with this email address already exists
    email= models.EmailField(verbose_name="Email Address")
    phone_number = models.CharField(validators=[validate_phone_number],max_length=14,verbose_name="Phone Number",blank=True,null=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_guest = models.BooleanField(default=False)
    key = models.TextField(blank=True,null=True)
    mobile_token = models.TextField(blank=True,null=True)
    from_mobile = models.BooleanField(default=False)
    otp = models.CharField(max_length=5,blank=True,null=True)
    no_email = models.BooleanField(default=False,verbose_name='No email/sms')
    pickup_notification = models.BooleanField(default=True)
    avg_per_day_order = models.IntegerField(default=1)
    api_token = models.BooleanField(default=False)
    tracking_code = models.CharField(max_length=4,blank=True,null=True)
    is_premium = models.BooleanField(default=False)
    company_name = models.CharField(max_length=64,blank=True,null=True)

    def __unicode__(self):
        return self.email

    def save(self, *args, **kwargs):
        if self.api_token and self.pk is not None:
            if self.mobile_token:
                pass
            else:
                self.mobile_token = str(generate_mobile_api_token(self.pk))+ str(self.pk)
        super(MainUser, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-date_joined']

class PickupAddress(models.Model):
    user = models.ForeignKey(MainUser,blank=True,null=True)
    name = models.CharField(max_length=128,verbose_name="Full Name")
    address_line = models.TextField()
    city = models.CharField(max_length=128,verbose_name="City / Town")
    state = models.CharField(max_length=128)
    pin_code = models.CharField(validators=[validate_pincode],max_length=6,verbose_name="Pincode")
    phone_number = models.CharField(validators=[validate_phone_number],max_length=14,verbose_name="Phone Number")

    def __unicode__(self):
        return self.user.email

    class Meta:
        ordering = ['-pk']
            
class DeliveryAddress(models.Model):
    user = models.ForeignKey(MainUser,blank=True,null=True)
    name = models.CharField(max_length=128,verbose_name="Full Name")
    address_line = models.TextField(verbose_name="Adress Details")
    city = models.CharField(max_length=128,verbose_name="City / Town")
    state = models.CharField(max_length=128)
    pin_code = models.CharField(validators=[validate_pincode],max_length=6,verbose_name="Pincode")
    phone_number = models.CharField(validators=[validate_phone_number],max_length=14,verbose_name="Phone Number")

    def __unicode__(self):
        return self.user.email

    class Meta:
        ordering = ['-pk']

pickrr/orders/forms.py
from django import forms
from users.models import MainUser
from django.contrib.auth.hashers import check_password
from helpers.helpers import get_or_none, filter_or_none
from django.contrib.admin import widgets


class UserTypeForm(forms.Form):
    email_field = forms.EmailField(label="Enter Email ID",required=True)
    CHOICES=[('guest','As guest user'),
         ('login_user','Login'),
         ('register_user','Register (Recommended for future convenience)')]
    proceed = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(),required=True)

class CheckoutLoginForm(forms.Form):
    password = forms.CharField(widget = forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(CheckoutLoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(CheckoutLoginForm, self).clean()
        user = self.user
        password = cleaned_data.get("password")
        if user and password:
            user = user.user
            if check_password(password,user.password):
                if not user.is_active:
                    msg = u"Your account has been deactivated.Please contact 09818197991 "
                    self._errors["password"] = self.error_class([msg])
                    # Password field is no longer valid.Thus, Remove it from the cleaned data.
                    del cleaned_data["email"]
            else:
                msg = u"Password did not match"
                self._errors["password"] = self.error_class([msg])
                # Password field is no longer valid.Thus, Remove it from the cleaned data.
                del cleaned_data["password"]
        # return full collection of cleaned data.
        return cleaned_data

class CheckoutSignupForm(forms.Form):
    password = forms.CharField(widget = forms.PasswordInput())
    confirm_password = forms.CharField(widget = forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        self.email = kwargs.pop('email', None)
        super(CheckoutSignupForm, self).__init__(*args, **kwargs)

    #Custom validation
    def clean(self):
        cleaned_data = super(CheckoutSignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        email = self.email
        if email:
            email_exist = get_or_none(MainUser,email=email,is_guest=False)
            if email_exist:
                #msg = u""
                #self._errors["email"] = self.error_class([msg])
                raise forms.ValidationError("This email ID is already registered.Either retrieve password or use different email ID")
                #del cleaned_data["email"]
        if password and confirm_password:
            if len(password) < 6:
                msg = u"Pasword must be of length greater than or equal to 6"
                self._errors["password"] = self.error_class([msg])
                del cleaned_data["password"]
            if password != confirm_password:
                msg = u"Pasword did not match"
                self._errors["confirm_password"] = self.error_class([msg])
                del cleaned_data["confirm_password"]
        return cleaned_data

class OrderDataUploadForm(forms.Form):
    user_account = forms.ModelChoiceField(queryset=MainUser.objects.none())
    #order_pickup_date = forms.DateTimeField(widget=widgets.AdminSplitDateTime)
    order_data = forms.FileField()

    def __init__(self, *args, **kwargs):
        #For dynamically changing the queryset of the field user_account!
        super(OrderDataUploadForm, self).__init__(*args, **kwargs)
        self.fields['user_account'].queryset = filter_or_none(MainUser,is_guest=False)


class BluedartWaybillForm(forms.Form):
    actual_weight = forms.DecimalField(label="Actual Weight")
    length = forms.IntegerField(label="Length")
    width = forms.IntegerField(label="Width")
    height = forms.IntegerField(label="Height")
    pickup_date_time = forms.DateTimeField()
    SUB_PRODUCT_CHOICES = [
        ("C", "Cash On Delivery"),
        ("P", "Prepaid")
    ]
    sub_product_type = forms.ChoiceField(choices=SUB_PRODUCT_CHOICES)
    PACKAGE_CHOICES = [
        ("Dutiables", "Dutiables"),
        ("Docs", "Documents")
    ]
    package_type = forms.ChoiceField(choices=PACKAGE_CHOICES)
    collectable_amount = forms.DecimalField(label="Collectable/Declared Amount")

pickrr/orders/templates/orders/bluedart_response.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta http-equiv="Content-Language" content="en">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
	<title>
		{% block title %}Pickrr | Reinventing your shipping experience{% endblock title%}
	</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<style type="text/css">
		@font-face{
			font-family: Basawa;
			src:url({% static "fonts/B39MHR.ttf" %});
		}
		.barcode{
			font-family: Basawa;
			font-size: 72px;
		}
	</style>

</head>
<body>
	<div class="container">
		<div class="row">
			{% if response_data.IsError = True %}
			<h3>You have an error. Have a look</h3>
			<p>
				{{ response_data}}
			</p>
			{% else %}
			<table class="table" style="margin-top: 1em;">
				<tbody>
					<tr>
						<td style="text-align: center; vertical-align: middle;border-right:0;width:30%;">
							<img src="{% static 'img/logo-f.svg' %}" alt="PICKRR">
						</td>
						<td style="border-left: 0;text-align: right;">
							<h3 style="margin-top: 0;">PICKRR</h3>
							<span>H.No - 2036/A</span><br/>
							<span>Sec-3, Near SRS value Bazaar</span><br/>
							<span>Faridabad - 121004</span><br/>
							<span>Phone no. - +91-9818197991</span>
						</td>
						<td >
							<span>
								<strong>ORDER NO.</strong> - {{ order.order_id }}
							</span><br/>

							<span>
								<strong>INVOICE DATE.</strong> - {{ waybill_data.pickup_date_time | date:"SHORT_DATE_FORMAT" }}
							</span><br/>
							<span>
								<strong>STN</strong> - BKTPG5735NSD001
							</span>
						</td>
						
					</tr>
					<tr>
						<td style="border-right: 0;">
							<h3><strong>DELIVER TO</strong></h3>
							<span>
								{{ order.drop_address.address_line }}
							</span><br/>
							<span>
								{{ order.drop_address.city }}, {{ order.drop_address.state}}
							</span><br/>
							<span>
								{{ order.drop_address.pin_code }} - <strong>{{ response_data.DestinationArea }}/{{ response_data.DestinationLocation }}</strong> 
							</span><br/>
							<span>
								Phone - {{ order.drop_address.phone_number }}
							</span>
						</td>
						<td colspan="2" style="text-align: center; border-left: 0;">
							<h3><strong>
								Order No. -
							</strong></h3>
							<h1 class="barcode">*{{ order.order_id }}*</h1>
						</td>
					</tr>
					<tr>
						<td colspan="3" style="text-align: center;border:0;">
							<h3><strong>
								{% if waybill_data.sub_product_type == 'C' %}
									CASH ON DELIVERY (COD)
								{% else %}
									PREPAID ORDER
								{% endif %}
							</strong></h3>
							<h1 class="barcode">*{{ response_data.AWBNo }}*</h1>
						</td>
					</tr>
					<tr>
						<td colspan="2" style="border:0; text-align: center;">
							{% if waybill_data.sub_product_type == 'C' %}
								<h3>
									<strong>
									AMOUNT TO BE COLLECTED
									</strong>
								</h3>
								<h3>
									Rs. {{ waybill_data.collectable_amount }}
								</h3>
							{% endif %}
						</td>
						<td style="border:0;">
							<span>
								<strong>AWB No.</strong> : {{ response_data.AWBNo }}
							</span><br/>
							<span>
								<strong>Weight</strong> : {{ waybill_data.actual_weight }}
							</span><br/>
							<span>
								<strong>Dimensions</strong> : {{ waybill_data.length }} X {{ waybill_data.width }} X {{ waybill_data.height }}
							</span><br/>
							<span>
								<strong>ORDER Id</strong> : {{ order.order_id }}
							</span><br/>
							<span>
								<strong>Order Date</strong> : {{ waybill_data.pickup_date_time | date:"SHORT_DATE_FORMAT" }}
							</span><br/>
							<span>
								<strong>Pieces</strong> : 1
							</span><br/>
						</td>
					</tr>
				</tbody>
			</table>
			<p>
				This is an electronically generated document, hence does not require signature.
			</p>
			<h4 style="border:2px solid; padding: 4px;">
				<strong>Return Address: </strong>
				PICKRR, H.No - 2036/A, Sec-3, Near SRS value Bazaar, Faridabad – 121004, DEL <br/>
				Phone No. + 91-919818197991
			</h4>
			
			{% endif %}
		</div>
	</div>
</body>

pickrr/orders/templates/orders/bluedart_waybill_generate.html
{% extends "__base.html" %}
{% block stylesheets %}
{{ block.super }}
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.4.5/jquery.datetimepicker.min.css">
{% endblock stylesheets %}
{% block body %}
<div class="form-legend shadow-z-2">
	<h3 class="form-heading">Bluedart Waybill Generator for #{{ order.order_id }}</h3>
	{% load widget_tweaks %}
	<form class="form-horizontal" method="POST">
		{% csrf_token %}
		{{ waybill_form.non_field_errors }}
		{% for field in waybill_form%}
		{% if field.errors %}
		<div class="form-group has-error">
			<label class="col-sm-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
			<div class="col-sm-9">
				{{ field| add_class:"form-control" }}
				<span class="help-block">
					{% for error in  field.errors %}{{ error }}{% endfor %}
				</span>
			</div>
		</div>
		{% else %}
		<div class="form-group">
			<label class="col-sm-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
			<div class="col-sm-9">
				{{ field| add_class:"form-control" }}
				{% if field.help_text %}
				<p class="help-block"><small>{{ field.help_text }}</small></p>
				{% endif %}
			</div>
		</div>
		{% endif %}
		{% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-4 col-sm-8">
			<button type="submit" class="btn btn-primary btn-raised">Generate Waybill</i></button>
			</div>
		</div>

	</form>
</div>
{% endblock body %}
{% block javascript %}
	{{ block.super }}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.4.5/jquery.datetimepicker.min.js" type="text/javascript"></script>
	<script type="text/javascript">
	jQuery(document).ready(function() {
		$("#id_pickup_date_time").datetimepicker({
			format: 'm/d/Y H:i'
			});
	});
	</script>
{% endblock javascript %}

pickrr/orders/templates/orders/checkout_delivery_address.html
<div class="panel-heading">
	<h3 class="panel-title">Tell us your Delivery Address</h3>
</div>
<div class="panel-body">
	{% load widget_tweaks %}
	<form action="{% url 'orders:checkout_delivery_address' %}" class="form-horizontal form-ajax" method="post">{% csrf_token %}
		{% for field in delivery_add_form %}
		{% if field.errors %}
		<div class="form-group has-error">
			<label class="col-sm-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
			<div class="col-sm-9">
				{{ field| add_class:"form-control" }}
				<span class="help-block">
					{% for error in  field.errors %}{{ error }}{% endfor %}
				</span>
			</div>
		</div>
		{% else %}
		<div class="form-group">
			<label class="col-sm-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
			<div class="col-sm-9">
				{{ field| add_class:"form-control" }}
				{% if field.help_text %}
				<p class="help-block"><small>{{ field.help_text }}</small></p>
				{% endif %}
			</div>
		</div>
		{% endif %}
		{% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-4 col-sm-8">
				<button name="add_delivery" type="submit" class="btn btn-primary btn-raised">Add Address &amp; Place Order</button>
			</div>
		</div>
	</form>
	{% if user.deliveryaddress_set.all.count != 0 %}
	<form action="{% url 'orders:checkout_delivery_address' %}" class="form-horizontal form-ajax" method="POST">{% csrf_token %}
		{% for delivery_address in user.deliveryaddress_set.all %}
		<div class="radio radio-success radio-rush radio-address">
			<label>
				<input type="radio" name="select_delivery" value="{{delivery_address.pk}}" required>
				<span class="circle"></span>
				<span class="check"></span>
				<div class="service-card">
					<strong>{{delivery_address.name}}</strong> 
					<p class="main-pricing">- {{delivery_address.city}}, {{delivery_address.state}}</p>
					<p class="pricing">
						<i>{{delivery_address.address_line}}</i> - 
						{{ delivery_address.pin_code }}
					</p>
				</div>
			</label>
			<div class="time-to">
				<i class="mdi-communication-call mat-icon"></i>
				{{delivery_address.phone_number}}
			</div>
		</div>
		{% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-4 col-sm-8">
				<button name="delivery_select" type="submit" class="btn btn-primary btn-raised">Select &amp; Place Order</button>
			</div>
		</div>
	</form>
	{% endif %}

</div>

pickrr/orders/templates/orders/checkout_flow.html
<div class="panel-heading">
    <h3 class="panel-title">Checkout Options</h3>
</div>
<div class="panel-body">
    {% load widget_tweaks %}
    <form class="form-ajax" method="POST" action="{% url 'orders:checkout_flow' %}">
        {% csrf_token %}
        <div class="form-control-wrapper">
            {{ user_type_form.email_field|add_class:"form-control empty" }}
            {% if user_type_form.email_field.errors %}
                {% for error in user_type_form.email_field.errors %}
                    <div class="help-block text-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            <div class="floating-label">{{ user_type_form.email_field.label }}</div>
        </div>
        <h3>Proceed as-</h3>
        <div class="form-radio-group">
            {% for field in user_type_form.proceed %}
            <div class="radio radio-primary radio-checkout">
                <label>
                    {{ field.tag }}<span class="circle"></span>
                    <span class="check"></span>
                    {{ field.choice_label }}
                </label>
            </div>
            {% endfor %}
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <button id="btn-checkout" type="submit" class="btn btn-primary btn-raised">Checkout</button>
            </div>
        </div>
    </form>
</div>

pickrr/orders/templates/orders/checkout_login_user.html
<form method="post">{% csrf_token %}
	{{checkout_login_form.as_p}}
	<button type="submit"> Login</button>
</form>

pickrr/orders/templates/orders/checkout_pickup_address.html
<div class="panel-heading">
	<h3 class="panel-title">Tell us your Pickup Address</h3>
</div>
<div class="panel-body">
	{% load widget_tweaks %}
	<form data-place="main-panel" action="{% url 'orders:checkout_pickup_address' %}" class="form-horizontal form-ajax" method="post">{% csrf_token %}
		{% for field in pickup_add_form %}
		{% if field.errors %}
		<div class="form-group has-error">
			<label class="col-sm-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
			<div class="col-sm-9">
				{{ field| add_class:"form-control" }}
				<span class="help-block">
					{% for error in  field.errors %}{{ error }}{% endfor %}
				</span>
			</div>
		</div>
		{% else %}
		<div class="form-group">
			<label class="col-sm-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
			<div class="col-sm-9">
				{{ field| add_class:"form-control" }}
				{% if field.help_text %}
				<p class="help-block"><small>{{ field.help_text }}</small></p>
				{% endif %}
			</div>
		</div>
		{% endif %}
		{% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-4 col-sm-8">
				<button name="add_pickup" type="submit" class="btn btn-primary btn-raised">Add Pickup Address </button>
			</div>
		</div>
	</form>
	{% if user.pickupaddress_set.all.count != 0 %}
	<form action="{% url 'orders:checkout_pickup_address' %}" class="form-horizontal form-ajax" method="POST">{% csrf_token %}
		{% for pickup_address in user.pickupaddress_set.all %}
		<div class="radio radio-success radio-rush radio-address">
            <label>
                <input type="radio" name="select_pickup" value="{{pickup_address.pk}}" required>
                <span class="circle"></span>
                <span class="check"></span>
                <div class="service-card">
                    <strong>{{pickup_address.name}}</strong> 
                    <p class="main-pricing">- {{pickup_address.city}}, {{pickup_address.state}}</p>
                    <p class="pricing">
                        <i>{{pickup_address.address_line}}</i> - 
                        {{ pickup_address.pin_code }}
                    </p>
                </div>
            </label>
            <div class="time-to">
                <i class="mdi-communication-call mat-icon"></i>
                {{pickup_address.phone_number}}
            </div>
        </div>
		{% endfor %}
		<div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <button name="pickup_select" type="submit" class="btn btn-primary btn-raised">Select &amp; Proceed</button>
            </div>
        </div>
	</form>
	{% endif %}
</div>

pickrr/orders/templates/orders/checkout_register_user.html
<form method="post">{% csrf_token %}
	{{checkout_signup_form.as_p}}
	<button type="submit"> Register</button>
</form>

pickrr/orders/templates/orders/order_data_upload_ops.html
<html>
<body>
<form enctype="multipart/form-data" method="post">{% csrf_token %}
	{{order_form.as_p}}
	<input type="submit" value="Upload"/>
</form>
</body>
</html>

pickrr/orders/templates/orders/pickup_order_placed.html
<div class="order-success">
    <h3>#{{order.order_id}} order Successfully Placed</h3>
    <p>Thanks for placing the <strong>{{order.service_used.service_name}}</strong> pickup order!</p>
    <p><strong>Tracking ID: {{track_obj.tracking_id}}</strong></p>
</div>
<div class="order-card shadow-z-2">
    <h4 class="text-center">Pickrr will be at your doorstep within 60 minutes</h4>
    <div class="row">
        <div class="col-md-12 text-center">
            <p>
                <span style="color:#16a085;">Pickrr:</span><i class="mdi-action-account-box mat-icon"></i> {{order.assigned_to.name}}
            </p>
        </div>
        <div class="col-md-6">
            <p>
                <i class="mdi-communication-phone mat-icon"></i> {{order.assigned_to.phone_number}}
            </p>
        </div>
        <div class="col-md-6">
            <p>
                <i class="mdi-communication-email mat-icon"></i> {{order.assigned_to.email_id}}
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
            <h3 class="panel-title">Pickup Address</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <p>
                        <strong>{{order.pickup_address.name}}</strong>
                    </p>
                </div>
                <div class="col-md-12">
                    Ph. - {{order.pickup_address.phone_number}}
                </div>
                <div class="col-md-12">
                    {{order.pickup_address.address_line}}
                </div>
                <div class="col-md-12">
                    {{order.pickup_address.city}},
                    {{order.pickup_address.state}}
                </div>
                <div class="col-md-6">
                    {{order.pickup_address.pin_code}}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
                <h3 class="panel-title">Delivery Address</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <p>
                        <strong>{{order.drop_address.name}}</strong>
                    </p>
                </div>
                <div class="col-md-12">
                    Ph. - {{order.drop_address.phone_number}}
                </div>
                <div class="col-md-12">
                    {{order.drop_address.address_line}}
                </div>
                <div class="col-md-12">
                    {{order.drop_address.city}},
                    {{order.drop_address.state}}
                </div>
                <div class="col-md-6">
                    {{order.drop_address.pin_code}}
                </div>
            </div>
        </div>
    </div>
</div>