pickrr/pickrr/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'pickrr.views.home', name='home'),
    url(r'^',include('pickup.urls',namespace='pickup')),
    url(r'^faqs/$', TemplateView.as_view(template_name='staticpages/faqs.html'), name='faq'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^order/',include('orders.urls',namespace='orders')),
    url(r'^tracking/',include('track.urls',namespace='track')),
    url(r'^api/',include('pickrr_common_api.urls',namespace='pickrr_common_api')),
    url(r'^price-calculator/',include('externalpriceapi.urls',namespace='externalpriceapi')),
    #url(r'^vendor-api/',include('vendorapi.urls',namespace='vendorapi')),
    url(r'^location/',include('locations.urls',namespace='locations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^weshyp/admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^weshyp/admin/', include(admin.site.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

pickrr/track/urls.py
from django.conf.urls import patterns, url
from track import views

urlpatterns = patterns('',
	url(r'^$',views.search_tracking,name='search_tracking'),
    url(r'^(?P<key>.+)/(?P<track_id>.+)/$',views.show_tracking,name='show_tracking'),
    url(r'^(?P<tracking_id>.+)/mobile/api$',views.tracking_api,name='tracking_api'),
)

pickrr/track/models.py
from django.db import models
import random
from helpers.helpers import send_sms, clean_phone_number

class Status(models.Model):
    tracking_id = models.CharField(max_length=64,blank=True,null=True)
    order = models.OneToOneField('orders.Order',blank=True,null=True)
    #is_picked = models.BooleanField(default=False)
    pickup_time = models.DateTimeField(blank=True,null=True)
    warehouse_receive_time = models.DateTimeField(blank=True,null=True)
    in_transit_time = models.DateTimeField(blank=True,null=True)
    in_transit_status = models.TextField(blank=True,null=True)
    out_delivery_time = models.DateTimeField(blank=True,null=True)
    #intermediate_status = models.CharField(max_length=64,default='In Transit',blank=True,null=True)
    #is_delivered = models.BooleanField(default=False)
    delivery_date = models.DateTimeField(blank=True,null=True)
    key = models.TextField(blank=True,null=True)

    def __unicode__(self):
        return str(self.order.order_id)

    def save(self, *args, **kwargs):
        if not self.tracking_id:
            n = 8
            self.tracking_id = ''.join(["%s" % random.randint(0, 9) for num in range(0, n)])
        #Sending an sms on pickup along with an invoice
        if self.pk is not None:
            if self.pickup_time is not None and self.order.user.pickup_notification:
                track_obj = Status.objects.get(pk=self.pk)
                #First time entry of pickup time
                if track_obj.pickup_time is None:
                    destination_number = clean_phone_number(self.order.pickup_address.phone_number)
                    if self.order.total_bill > float(0):
                        total_bill = self.order.total_bill
                    else:
                        total_bill = None
                    first_line = 'Dear ' + self.order.pickup_address.name + ',' + '\n'
                    if self.order.user.email == 'contact@wishup.in':
                        second_line = ('Thank you for placing your order on Wishup.',
                                'Your parcel for the order',
                                '#%s'%self.order.order_id,
                                'has been successfully picked by our logistics partner Pickrr on',
                                self.pickup_time.strftime("%B %d, %y, %H:%M"))
                    else:
                        second_line = ('Your parcel for the order',
                                '#%s'%self.order.order_id,
                                'has been successfully picked by Pickrr on',
                                self.pickup_time.strftime("%B %d, %y, %H:%M"))
                    second_line = ' '.join(second_line)
                    second_line = second_line + '.' + '\n' + '\n'
                    fourth_line = ('You can track your shipment on http://www.pickrr.com via your tracking ID',
                                    self.tracking_id)
                    fourth_line = ' '.join(fourth_line)
                    fourth_line += '.'
                    if total_bill is not None:
                        third_line = ('Your Total invoice amount was',
                                    'Rs',
                                    str(total_bill))
                        third_line = ' '.join(third_line)
                        third_line = third_line + '.' + '\n' + '\n'
                        message = first_line + second_line + third_line + fourth_line
                    else:
                        message = first_line + second_line + fourth_line
                    send_sms(destination_number,message)
            #second sms on succesfull delivery
            if self.delivery_date is not None:
                track_obj = Status.objects.get(pk=self.pk)
                #First time entry of pickup time
                if track_obj.delivery_date is None:
                    if self.order.user.email == 'archies@pickrr.com':
                        destination_number = clean_phone_number(self.order.drop_address.phone_number)
                        first_line = 'Dear ' + self.order.drop_address.name + ',' + '\n'
                    else:
                        destination_number = clean_phone_number(self.order.pickup_address.phone_number)
                        first_line = 'Dear ' + self.order.pickup_address.name + ',' + '\n'
                    if self.order.user.email == 'contact@wishup.in':
                        second_line = ('Thanks for choosing Wishup.',
                                'Your parcel for the order',
                                '#%s'%self.order.order_id,
                                'has been successfully delivered by our logistics partner Pickrr on',
                                self.delivery_date.strftime("%B %d, %y, %H:%M"))
                    else:
                        second_line = ('Your parcel for the order',
                                '#%s'%self.order.order_id,
                                'has been successfully delivered by Pickrr on',
                                self.delivery_date.strftime("%B %d, %y, %H:%M"))
                    second_line = ' '.join(second_line)
                    second_line = second_line + '.'
                    third_line = 'Check out our android app at https://goo.gl/xR4U8e'
                    message = first_line + second_line + third_line
                    send_sms(destination_number,message)
        super(Status, self).save(*args, **kwargs)

pickrr/track/forms.py
from django import forms
from helpers.helpers import get_or_none
#from orders.models import Order
from track.models import Status

class TrackingForm(forms.Form):
    #email = forms.EmailField(label='Enter Checkout Email ID',required=True)
    tracking_id = forms.CharField(label='Enter Tracking ID',required=True)

    #Custom validation
    def clean(self):
        cleaned_data = super(TrackingForm, self).clean()
        tracking_id = cleaned_data.get("tracking_id")
        #order_id = cleaned_data.get("order_id")
        if tracking_id:
            track_obj = get_or_none(Status,tracking_id=tracking_id)
            if not track_obj:
                msg = u"Invalid Tracking ID"
                self._errors["tracking_id"] = self.error_class([msg])
                del cleaned_data["tracking_id"]
        return cleaned_data

pickrr/track/views.py
from django.shortcuts import render_to_response,redirect, get_object_or_404, Http404
from django.template import RequestContext
from track.forms import TrackingForm
from track.models import Status
from orders.models import Order
from users.views import key_gen
from helpers.helpers import JsonResponse, correction_in_time

def search_tracking(request):
    trackingform = TrackingForm()
    if request.method=='POST':
        trackingform = TrackingForm(request.POST)
        if trackingform.is_valid():
            tracking_id = trackingform.cleaned_data['tracking_id']
            track_obj = get_object_or_404(Status,tracking_id=tracking_id)
            if not track_obj.key:
                track_obj.key = key_gen(track_obj.pk)
                track_obj.save()
            return redirect('track:show_tracking',track_obj.key,track_obj.pk)
    return render_to_response('track/search_tracking.html',
                            {'trackingform':trackingform},
                            context_instance=RequestContext(request))

def show_tracking(request,key,track_id):
    track_obj = get_object_or_404(Status,pk=track_id)
    if str(track_obj.key) != str(key):
        raise Http404
    return render_to_response('track/show_tracking.html',
                            {'track_obj':track_obj},
                            context_instance=RequestContext(request))

def tracking_api(request,tracking_id):
    track_obj = get_object_or_404(Status,tracking_id=str(tracking_id))
    response_data = {}
    response_data['order_status'] = 'Placed on ' + correction_in_time(track_obj.order.placed_at)
    if track_obj.pickup_time:
        response_data['pickup_status'] = 'Picked on ' + correction_in_time(track_obj.pickup_time)
    if track_obj.warehouse_receive_time:
        response_data['warehouse_status'] = 'Reached Pickrr Warehouse on ' + correction_in_time(track_obj.warehouse_receive_time)
    if track_obj.in_transit_time:
        if track_obj.in_transit_status:
            response_data['transit_status'] = str(track_obj.in_transit_status) + ' from ' + correction_in_time(track_obj.in_transit_time)
        else:
            response_data['transit_status'] = 'In Transit from ' + correction_in_time(track_obj.in_transit_time)
    if track_obj.out_delivery_time:
        response_data['delivery_status'] = 'Out for Delivery from ' + correction_in_time(track_obj.out_delivery_time)
    if track_obj.delivery_date:
        response_data['final_status'] = 'Successfully Delivered on ' + correction_in_time(track_obj.delivery_date)
    return JsonResponse(response_data)

pickrr/track/templates/track/search_tracking.html
<form class="form-horizontal form-ajax" action="{% url 'track:search_tracking' %}" method="post">{% csrf_token %}
    {% load widget_tweaks %}
    {% for field in trackingform %}
    {% if field.errors %}
    <div class="form-group has-error">
        <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="col-sm-8">
            {{ field| add_class:"form-control" }}
            <span class="help-block">
                {% for error in  field.errors %}{{ error }}{% endfor %}
            </span>
        </div>
    </div>
    {% else %}
    <div class="form-group">
        <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="col-sm-8">
            {{ field| add_class:"form-control" }}
            {% if field.help_text %}
            <p class="help-block"><small>{{ field.help_text }}</small></p>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
            <button type="submit" class="btn btn-primary btn-raised">
                Track Order
            </button>
        </div>
    </div>
</form>

pickrr/track/templates/track/show_tracking.html
<h4>Order Id - <strong>#{{ track_obj.order.order_id }}</strong></h4>
<div class="status-wrap clearfix text-center">
    <div class="col-md-2" style="border-right: 1px solid #009688">
        <h4>Order Status:</h4>
        <i class="mdi-toggle-radio-button-on"></i>
        <span class="status">
            Placed on {{ track_obj.order.placed_at }}
        </span>
    </div>
    <div class="col-md-2 {% if not track_obj.pickup_time %}unactive{% endif %}" style="border-right:1px solid;">
        <h4>Pickup Status:</h4>
        {% if track_obj.pickup_time %}
            <i class="mdi-toggle-radio-button-on"></i>
            <span class="status">
                Picked on {{track_obj.pickup_time}}
            </span>
        {% else %}
            <i class="mdi-image-lens" style="font-size:1em;"></i>
            <span class="status" >
                Not yet Picked Up
            </span>
        {% endif %}
    </div>
    <div class="col-md-2 {% if not track_obj.warehouse_receive_time %}unactive{% endif %}" style="border-right:1px solid;">
        <h4>Warehouse:</h4>
        {% if track_obj.warehouse_receive_time %}
            <i class="mdi-toggle-radio-button-on"></i>
            <span class="status">
                Reached Pickrr Warehouse on {{track_obj.warehouse_receive_time}}
            </span>
        {% else %}
            <i class="mdi-image-lens" style="font-size:1em;"></i>
            <span class="status">
                --NA--
            </span>
        {% endif %}
    </div>
    <div class="col-md-2 {% if not track_obj.in_transit_time %}unactive{% endif %}" style="border-right:1px solid;">
        <h4>Transit Status:</h4>
        {% if track_obj.in_transit_time %}
            <i class="mdi-toggle-radio-button-on"></i>
            <span class="status">
                {% if track_obj.in_transit_status %}
                    {{track_obj.in_transit_status}} from {{track_obj.in_transit_time}}
                {% else %}
                    In Transit at from {{track_obj.in_transit_time}}
                {% endif %}
            </span>
        {% else %}
            <i class="mdi-image-lens" style="font-size:1em;"></i>
            <span class="status">
                --NA--
            </span>
        {% endif %}
    </div>
    <div class="col-md-2 {% if not track_obj.out_delivery_time %}unactive{% endif %}" style="border-right:1px solid;">
        <h4>Delivery Status:</h4>
        {% if track_obj.out_delivery_time %}
            <i class="mdi-toggle-radio-button-on"></i>
            <span class="status">
                Out for Delivery from {{track_obj.out_delivery_time}}
            </span>
        {% else %}
            <i class="mdi-image-lens" style="font-size:1em;"></i>
            <span class="status">
                --NA--
            </span>
        {% endif %}
    </div>
    <div class="col-md-2 {% if not track_obj.delivery_date %}unactive{% endif %}">
        <h4>Final Status:</h4>
        {% if track_obj.delivery_date %}
            <i class="mdi-toggle-radio-button-on"></i>
            <span class="status">
                Successfully Delivered on {{track_obj.delivery_date}}
            </span>
        {% else %}
            <i class="mdi-image-lens" style="font-size:1em;"></i>
            <span class="status">
                --NA--
            </span>
        {% endif %}
    </div>
</div>