pickrr/pickrr/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'pickrr.views.home', name='home'),
    url(r'^',include('pickup.urls',namespace='pickup')),
    url(r'^faqs/$', TemplateView.as_view(template_name='staticpages/faqs.html'), name='faq'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^order/',include('orders.urls',namespace='orders')),
    url(r'^tracking/',include('track.urls',namespace='track')),
    url(r'^api/',include('pickrr_common_api.urls',namespace='pickrr_common_api')),
    url(r'^price-calculator/',include('externalpriceapi.urls',namespace='externalpriceapi')),
    #url(r'^vendor-api/',include('vendorapi.urls',namespace='vendorapi')),
    url(r'^location/',include('locations.urls',namespace='locations')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^weshyp/admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^weshyp/admin/', include(admin.site.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

pickrr/pickup/urls.py
from django.conf.urls import patterns, url
from pickup import views

urlpatterns = patterns('',
    url(r'^$',views.home_pickrr,name='home_pickrr'),
    url(r'^select-service/$',views.select_service,name='select_service'),
    url(r'^(?P<from_location_id>.+)/(?P<to_location_id>.+)/show-service-api/$',views.show_service_api,name='show_service_api'),
)

pickrr/track/urls.py
from django.conf.urls import patterns, url
from track import views

urlpatterns = patterns('',
	url(r'^$',views.search_tracking,name='search_tracking'),
    url(r'^(?P<key>.+)/(?P<track_id>.+)/$',views.show_tracking,name='show_tracking'),
    url(r'^(?P<tracking_id>.+)/mobile/api$',views.tracking_api,name='tracking_api'),
)

pickrr/users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^signup/$',views.user_signup,name='user_signup'),
    url(r'^login/$',views.user_login,name='user_login'),
    url(r'^account/$',views.user_account,name='user_account'),
    url(r'^account/edit/$',views.user_account_edit,name='user_account_edit'),
    url(r'^(?P<user_id>.+)/(?P<auth_token>.+)/account-edit-api/$',views.mobile_edit_account,name='mobile_edit_account'),
    url(r'^logout/$',views.user_logout,name='user_logout'),
    url(r'^addresses/$',views.view_add_address,name='view_add_address'),
    url(r'^change-password/$',views.user_change_password,name='user_change_password'),
    url(r'^bookings/$',views.pickup_bookings,name='pickup_bookings'),
    url(r'^forgot-password/$',views.forgot_password,name='forgot_password'),
    url(r'^forgot-password/info/$',views.forgot_password_link_info,name='forgot_password_link_info'),
    url(r'^(?P<key>.+)/(?P<user_id>.+)/set-password/$',views.set_password,name='set_password'),
    url(r'^(?P<user_id>.+)/(?P<auth_token>.+)/pick-address-all/api/$',views.all_pickup_address_api,name='all_pickup_address_api'),
    url(r'^(?P<user_id>.+)/(?P<auth_token>.+)/drop-address-all/api/$',views.all_drop_address_api,name='all_drop_address_api'),
    url(r'^mobile-auth-api/$',views.mobile_auth_api,name='mobile_auth_api'),
    url(r'^mobile-auth-api-otp/$',views.mobile_auth_api_otp,name='mobile_auth_api_otp'),
    url(r'^(?P<user_id>.+)/mobile-auth-api-otp-resend/$',views.mobile_auth_api_otp_resend,name='mobile_auth_api_otp_resend'),
)

pickrr/orders/models.py
from django.db import models

class Order(models.Model):
    #order_id += order.pk
    order_id = models.CharField(max_length=256)
    user = models.ForeignKey('users.MainUser')
    pickup_address = models.ForeignKey('users.PickupAddress')
    drop_address = models.ForeignKey('users.DeliveryAddress')
    service_used = models.ForeignKey('pricingmodel.PickrrServices',blank=True,null=True)
    placed_at = models.DateTimeField(auto_now_add=True)
    scheduled_for = models.DateTimeField(blank=True,null=True)
    placed_at.editable = True
    total_bill = models.FloatField(default=0)
    invoice_sent = models.BooleanField(default=False)
    assigned_to = models.ForeignKey('pickrrs.Pickrrs',blank=True,null=True)
    is_cod = models.BooleanField(default=False)
    cod_amount = models.FloatField(default=0)
    is_cancelled = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.order_id)

    class Meta:
        ordering = ['-placed_at']

class OrderItems(models.Model):
    order = models.ForeignKey('Order')
    product = models.ForeignKey('products.Product',blank=True,null=True)
    quantity = models.IntegerField(default=1)
    length = models.FloatField(default=0)
    breadth = models.FloatField(default=0)
    height = models.FloatField(default=0)
    weight = models.FloatField(default=0.5)
    item_bill = models.FloatField(default=0)

    def __unicode__(self):
        return self.order.user.email

    class Meta:
        ordering = ['-pk']

pickrr/users/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect, get_list_or_404, Http404
from django.core.urlresolvers import reverse
from django.template import Context, RequestContext
from django.core.context_processors import csrf
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from users.models import MainUser, PickupAddress, DeliveryAddress
from users.forms import SignupForm, LoginForm, PickupAddressForm, DeliveryAddressForm, ChangePasswordForm, ProfileEditForm, ForgotPasswordForm, SetPasswordForm
from orders.models import Order
#from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
import random
import string
from datetime import datetime, timedelta
import math
import hashlib
import json
from django.utils import timezone
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from locations.models import City
from helpers.helpers import read_post_json, JsonResponse, send_sms, clean_phone_number, generate_otp, generate_mobile_api_token, JsonQueryset
from django.views.decorators.csrf import csrf_exempt

User = get_user_model()

def key_gen(key):
    myvar = ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits + string.ascii_uppercase) for _ in range(8))
    myvar += str(key)
    ckey = hashlib.md5(myvar).hexdigest()
    if not ckey:
        return key
    else:
        return ckey

#Signup View
def user_signup(request):
    signupform = SignupForm()
    if request.method=='POST':
        signupform = SignupForm(request.POST)
        if signupform.is_valid():
            password = signupform.cleaned_data['password']
            signup = signupform.save(commit=False)
            signup.save()
            #Max length of auth user is 30
            username = 'mainuser' + str(signup.pk)
            #creating a user object corresponding to the customer user
            user = User.objects.create_user(username,signup.email,password)
            user.is_active = True
            user.save()
            signup.user = user
            signup.save()
            #No verification email for now
            #Authenticate the user and allow login directly
            main_user = authenticate(username=username, password=password)
            if main_user is not None:
                if main_user.is_active:
                    login(request,main_user)
                    #successful login
                    if request.session.get('service_id',False):
                        request.session['user_id'] = signup.pk
                        return redirect('orders:checkout_pickup_address')
                    return HttpResponse(json.dumps({
                        "login": True
                        }), content_type="application/json")
                else:
                    return HttpResponse('Your account has been deactivated. Please contact 09818197991')
            else:
                #invalid email or password
                return HttpResponse('invalid email or password')
            #return redirect('users:user_account')
    return render_to_response('users/_user_signup.html',
                            {'signupform':signupform},
                            context_instance=RequestContext(request))

#Login View
def user_login(request):
    loginform = LoginForm()
    if request.method=='POST':
        loginform = LoginForm(request.POST)
        if loginform.is_valid():
            email = loginform.cleaned_data['email']
            password = loginform.cleaned_data['password']
            user_obj = get_object_or_404(MainUser,email=email,is_guest=False)
            main_user = authenticate(username=user_obj.user.username, password=password)
            if main_user is not None:
                if main_user.is_active:
                    login(request,main_user)
                    if request.session.get('service_id',False):
                        request.session['user_id'] = user_obj.pk
                        return redirect('orders:checkout_pickup_address')
                    #successful login
                    return HttpResponse(json.dumps({
                        "login": True
                        }), content_type="application/json")
                else:
                    return HttpResponse('Your account has been deactivated. Please contact 09818197991')
            else:
                #invalid email or password
                return HttpResponse('invalid email or password')
    return render_to_response('users/_user_login.html',
                            {'loginform':loginform},
                            context_instance=RequestContext(request))

def forgot_password(request):
    if request.user.is_authenticated():
        return redirect('users:user_account')
    forgot_password_form = ForgotPasswordForm()
    if request.method=='POST':
        forgot_password_form = ForgotPasswordForm(request.POST)
        if forgot_password_form.is_valid():
            email = forgot_password_form.cleaned_data['email']
            user_obj = get_object_or_404(MainUser,email=email,is_guest=False)
            if not user_obj.key:
                user_obj.key = key_gen(user_obj.pk)
                user_obj.save()
            set_link = 'http://www.pickrr.com/users/' + str(user_obj.key) + '/' + str(user_obj.pk) + '/set-password/'
            subject = "Set Password Link for " + str(email)
            body = render_to_string('users/set_password_email.html', {'user_obj':user_obj,'set_link':set_link})
            email = EmailMessage(subject, body, to=[user_obj.email])
            email.content_subtype = "html"
            email.send()
            return redirect('users:forgot_password_link_info')
    return render_to_response('users/forgot_password.html',
                            {'forgot_password_form':forgot_password_form},
                            context_instance=RequestContext(request))

def forgot_password_link_info(request):
    return render_to_response('users/forgot_password_link_info.html',
                            context_instance=RequestContext(request))

def set_password(request,key,user_id):
    if request.user.is_authenticated():
        return redirect('users:user_account')
    user = get_object_or_404(MainUser,pk=user_id)
    if str(user.key) != str(key):
        raise Http404
    set_password_form = SetPasswordForm(user_id=user_id)
    if request.method=='POST':
        set_password_form = SetPasswordForm(request.POST,user_id=user_id)
        if set_password_form.is_valid():
            return redirect('pickup:home_pickrr')
    return render_to_response('users/set_password.html',
                            {'set_password_form':set_password_form},
                            context_instance=RequestContext(request))

#User Account
@login_required(login_url='/users/login/')
def user_account(request):
    user_obj = get_object_or_404(MainUser,user=request.user)
    pickup_list = user_obj.pickupaddress_set.all()
    drop_list = user_obj.deliveryaddress_set.all()
    orders = Order.objects.filter(user=user_obj)
    return render_to_response('users/user_account.html',
                            {'pickup_list': pickup_list,
                            'drop_list': drop_list,
                            'orders': orders},
                            context_instance=RequestContext(request))

#User Account Edit view
@login_required(login_url='/users/login/')
def user_account_edit(request):
    user_obj = get_object_or_404(MainUser,user=request.user)
    account_edit_form = ProfileEditForm(instance=user_obj)
    if request.method=='POST':
        account_edit_form = ProfileEditForm(request.POST,instance=user_obj)
        if account_edit_form.is_valid():
            account_edit_form.save()
            return redirect('users:user_account')
    return render_to_response('users/user_account_edit.html',
                            {'account_edit_form':account_edit_form},
                            context_instance=RequestContext(request))

#User Account pickup bookings
@login_required(login_url='/users/login/')
def pickup_bookings(request):
    user_obj = get_object_or_404(MainUser,user=request.user)
    bookings = user_obj.order_set.all()
    return render_to_response('users/pickup_bookings.html',
                            {'bookings':bookings},
                            context_instance=RequestContext(request))

#Logout View
@login_required(login_url='/users/login')
def user_logout(request):
    logout(request)
    return redirect('pickup:home_pickrr')

#change password view
@login_required(login_url='/users/login')
def user_change_password(request):
    change_password_form = ChangePasswordForm(request=request)
    if request.method=='POST':
        change_password_form = ChangePasswordForm(request.POST,request=request)
        if change_password_form.is_valid():
            return redirect('users:user_account')
    return render_to_response('users/user_change_password.html',
                            {'change_password_form':change_password_form},
                            context_instance=RequestContext(request))

#Add address View
@login_required(login_url='/users/login')
def view_add_address(request):
    user_obj = get_object_or_404(MainUser,user=request.user)
    pickup_list = user_obj.pickupaddress_set.all()
    drop_list = user_obj.deliveryaddress_set.all()
    pickupform = PickupAddressForm()
    deliveryform = DeliveryAddressForm()
    if 'pickup_form' in request.POST:
        pickupform = PickupAddressForm(request.POST)
        if pickupform.is_valid():
            pickup_info = pickupform.save(commit=False)
            pickup_info.user=user_obj
            from_city = pickupform.cleaned_data['from_city']
            #from_state = pickupform.cleaned_data['from_state']

pickrr/users/templates/users/_user_login.html
<form class="form-horizontal form-ajax" action="{% url 'users:user_login' %}" method="post">{% csrf_token %}
    {% load widget_tweaks %}
    {% for field in loginform %}
    {% if field.errors %}
    <div class="form-group has-error">
        <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="col-sm-8">
            {{ field| add_class:"form-control" }}
            <span class="help-block">
                {% for error in  field.errors %}{{ error }}{% endfor %}
            </span>
        </div>
    </div>
    {% else %}
    <div class="form-group">
        <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="col-sm-8">
            {{ field| add_class:"form-control" }}
            {% if field.help_text %}
            <p class="help-block"><small>{{ field.help_text }}</small></p>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <div class="form-group">
        <div class="pull-right">
            <a class="slick-link" href="{% url 'users:forgot_password' %}" target="_blank">Forgot Password</a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
            <button type="submit" class="btn btn-primary btn-raised">
                Login
            </button>
        </div>
    </div>
</form>

pickrr/users/templates/users/_user_signup.html
<form class="form-horizontal form-ajax" action="{% url 'users:user_signup' %}" method="post">{% csrf_token %}
    {% load widget_tweaks %}
    {% for field in signupform %}
    {% if field.errors %}
    <div class="form-group has-error">
        <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="col-sm-8">
            {{ field| add_class:"form-control" }}
            <span class="help-block">
                {% for error in  field.errors %}{{ error }}{% endfor %}
            </span>
        </div>
    </div>
    {% else %}
    <div class="form-group">
        <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div class="col-sm-8">
            {{ field| add_class:"form-control" }}
            {% if field.help_text %}
            <p class="help-block"><small>{{ field.help_text }}</small></p>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
            <button type="submit" class="btn btn-primary btn-raised">
                Register
            </button>
        </div>
    </div>
</form>

pickrr/users/templates/users/forgot_password.html
{% extends "__base.html" %}
{% block body %}
<section id="landing">
    <div class="content-holder">
        <div class="col-md-12" data-position="center" id="pickrr-panel">
    <div class="panel panel-main panel-ajax shadow-z-2">
        <div class="panel-heading">
            <h3 class="panel-title">Submit Email to Reset Password</h3>
        </div>
        <div class="panel-body">
            {% load widget_tweaks %}
            <form action="{% url 'users:forgot_password'  %}" class="form-horizontal form-ajax" method="post">{% csrf_token %}
                {% for field in forgot_password_form %}
                {% if field.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-8">
                        {{ field| add_class:"form-control" }}
                        <span class="help-block">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-8">
                        {{ field| add_class:"form-control" }}
                        {% if field.help_text %}
                        <p class="help-block"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary btn-raised">
                            Send Reset Link
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
    </div>
</section>
{% endblock body %}

pickrr/users/templates/users/forgot_password_link_info.html
<div class="panel-heading">
    <h3 class="panel-title">Password Reset Done! -</h3>
</div>
<div class="panel-body">
    <h4>
        <strong>Password reset link has been set to your registered mail ID.</strong>
    </h4>
</div>

pickrr/users/templates/users/order_placed_email.html
Hi
{% if order.user.name %}
	{{order.user.name}}
{% else %}
	{{order.user.email}}
{% endif %},
<br>
{% if order.is_cancelled %}
	Your order <B>#{{order.order_id}}</B> has been successfully cancelled as per your request.We regret of not been able to serve you this time. Looking forward to serve you in near future.
{% else %}
	Thanks for placing the <B>#{{order.order_id}}</B> pickup order!
<br>
<B>Tracking ID: {{track_obj.tracking_id}}</B>
{% if order.scheduled_for %}
<br><br>
Order Pickup Scheduled Time : {{order.scheduled_for}}
{% endif %}
{% for item in order.orderitems_set.all %}
<br><br>
Item Details:
	<ul>
		<li>
			{{item}}
		</li>
	</ul>
{% endfor %}
{% if coupon_code %}
<br><br>
<B> Coupon Applied : </B> {{coupon_code}}
{% endif %}
<br><br>
Following Pickrr will pickup your shipment:
<br>
{{order.assigned_to.name}}
<br>
{{order.assigned_to.phone_number}}
<br>
{{order.assigned_to.email_id}}
<br><br>
Order Details:
<br>
Pickup Address:<br>
{{order.pickup_address.name}}<br>
{{order.pickup_address.phone_number}}<br>
{{order.pickup_address.address_line}}<br>
{{order.pickup_address.city}}<br>
{{order.pickup_address.state}}<br>
{{order.pickup_address.pin_code}}
<br><br>
Delivery Address:<br>
{{order.drop_address.name}}<br>
{{order.drop_address.phone_number}}<br>
{{order.drop_address.address_line}}<br>
{{order.drop_address.city}}<br>
{{order.drop_address.state}}<br>
{{order.drop_address.pin_code}}
<br><br>
Service Selected:
<B>
	{% if order.service_used.service_zone.zone_name == "Intracity" %}
		{{order.service_used.service_name}} | Intracity
	{% else %}
		{{order.service_used.service_name}} | Inter-city
	{% endif %}
</B>
<br><br>
Service Pricing Plan:<br>
<B>
	Rs {{ order.service_used.base_price }} for first {{ order.service_used.base_weight }} Kg<br>
	Rs {{ order.service_used.add_price }} per additional {{ order.service_used.base_weight }} Kgs
</B>
{% endif %}
<br><br>
Your feedback about our service is most welcomed. For any query, feel free to reach us out at +91-9818197991
<br><br>
Thanks,<br>
Team, Pickrr<br>
"We Pick, Pack and Deliver"

pickrr/users/templates/users/pickup_bookings.html
{% for order in bookings %}
{{order.pickup_address.city}} - {{order.drop_address.city}}
<br>
{{order.service_used.service_name}}
<br>
Placed On: {{order.placed_at}}
<br>
{% if order.invoice_sent %}
	Bill: Rs {{order.total_bill}}
{% else %}
	In Process
{% endif %} 
<br>
Pickrr Assigned: {{order.assigned_to.name}} | {{order.assigned_to.phone_number}}
<br><br>
{% endfor %}

pickrr/users/templates/users/set_password.html
{% extends "__base.html" %}
{% block body %}
<div class="col-md-12" data-position="center" id="pickrr-panel">
    <div class="panel panel-main panel-ajax shadow-z-2">
        <div class="panel-heading">
            <h3 class="panel-title">Set a New Password</h3>
        </div>
        <div class="panel-body">
            {% load widget_tweaks %}
            <form  class="form-horizontal" method="post">{% csrf_token %}
                {% for field in set_password_form %}
                {% if field.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-8">
                        {{ field| add_class:"form-control" }}
                        <span class="help-block">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-8">
                        {{ field| add_class:"form-control" }}
                        {% if field.help_text %}
                        <p class="help-block"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary btn-raised">
                            Reset Password
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

pickrr/users/templates/users/set_password_email.html
{% if user_obj.name %}
	Hi {{user_obj.name}},
{% else %}
	Hi {{user_obj.email}},
{% endif %}
<br><br>
Click on the following to retrieve your password:<br>
{{set_link}}
<br><br>
Regards,
<br>
Team, Pickrr<br>
"We Pick, Pack and Deliver"

pickrr/users/templates/users/user_account.html
{% extends "__base.html" %}
{% block body %}
<div class="content-padder">
  <ul class="nav nav-tabs pickrr-tab">
    <li class="active">
      <a href="#home" data-toggle="tab" aria-expanded="true">Orders</a>
    </li>
    <li class="">
      <a href="#profile" data-toggle="tab" aria-expanded="false">Addresses</a>
    </li>
  </ul>
  <div class="action-btn">
    <a href="{% url 'pickup:home_pickrr' %}" class="btn btn-fab btn-raised btn-dafault" data-toggle="tooltip" data-placement="left" title="Schedule a new Pickup">
      <i class="mdi-content-add"></i>
    </a>
  </div>
  <div id="myTabContent" class="tab-content pickrr-tab-content clearfix shadow-z-2">
    <div style="" class="tab-pane fade active in" id="home">
      <h3 style="margin-top:0;color:#009688">Your order History</h3>
      {% for order in orders %}
      <div class="col-md-12">
        <div class="order-wrapper shadow-z-1">
          <div class="order-his">
            <div class="order-detail">
             Order -  <strong>#{{ order.order_id }}</strong>
           </div>
           <div class="order-detail">
             Tracking Id -  <strong>#{{ order.status.tracking_id }}</strong>
           </div>
           <div class="order-money">
             {% if order.invoice_sent %}
             <i class="mdi-action-receipt"></i> Rs {{order.total_bill}}
             {% else %}
             In Process
             {% endif %}
           </div>
         </div>

         <div class="order-dir">
          <span>{{ order.pickup_address.city |lower|capfirst }}</span>
          to
          <span>{{ order.drop_address.city |lower|capfirst }}</span>
        </div>
        <div class="track-dir">
            <button ajax-href="{% url 'track:show_tracking' order.status.key order.status.pk %}" data-loading-text="Tracking" class="btn btn-default btn-raised btn-sm btn-track">
              Track Package 
            </button>
            <div class="track-data">
              
            </div>
          </div>
        <div class="order-time">
         <i class="mdi-action-event"></i> {{ order.placed_at|timesince }} ago
       </div>
     </div>
   </div>
   {% endfor %}
 </div>

 <div class="tab-pane fade" id="profile">
  <h3 style="margin-top:0px;color:#009688;">Your Address store</h3>
  <div class="col-md-6">
    <h4>Pickup Addresses</h4>
    <div class="list-group">
      {% for pickup_address in pickup_list %}
      <div class="list-group-item list-address">
        <div class="list-group-item-heading">
          {{ pickup_address.name }} - <span class="tel">{{ pickup_address.phone_number }}</span>
        </div>
        <div class="list-group-item-text">
          {{ pickup_address.address_line }}, 
          {{ pickup_address.city }}, {{ pickup_address.state }}
          <span class="pin">{{ pickup_address.pin_code }}</span>
        </div>

      </div>
      {% endfor %}
    </div>
  </div>
  <div class="col-md-6">
    <h4>Delivery Addresses</h4>
    <div class="list-group">
      {% for delivery_address in drop_list %}
      <div class="list-group-item list-address">
        <div class="list-group-item-heading">
          {{ delivery_address.name }} - <span class="tel">{{ delivery_address.phone_number }}</span>
        </div>
        <div class="list-group-item-text">
          {{ delivery_address.address_line }}, 
          {{ delivery_address.city }}, {{ delivery_address.state }}
          <span class="pin">{{ delivery_address.pin_code }}</span>
        </div>

      </div>
      {% endfor %}
    </div>
  </div>
</div>
</div>  
</div>


{% endblock body %}

pickrr/users/templates/users/view_add_address.html
Pickup Address:<br>
{% for pickup in pickup_list %}
{{pickup.name}}<br>
{{pickup.phone_number}}<br>
{{pickup.address_line}}<br>
{{pickup.city}}<br>
{{pickup.state}}<br>
{{pickup.pin_code}}
<br><br>
{% endfor %}
<br></br>
<form method="post">{% csrf_token %}
	{{ pickupform.as_p }}
	<button name = "pickup_form" type="submit">Add Pickup Address</button>
</form>
<br><br>
Delivery Address:<br>
{% for delivery in drop_list %}
{{delivery.name}}<br>
{{delivery.phone_number}}<br>
{{delivery.address_line}}<br>
{{delivery.city}}<br>
{{delivery.state}}<br>
{{delivery.pin_code}}
<br><br>
{% endfor %}
<br>
<form method="post">{% csrf_token %}
	{{ deliveryform.as_p }}
	<button name = "delivery_form" type="submit">Add Delivery Address</button>
</form>

pickrr/users/templates/users/welcome_mobile_to_web.html
Hi {{user_obj.name}},
<br><br>
Welcome to Pickrr!<br>
Thanks for believing in us by registering on our mobile app. We also have a website located at http://www.pickrr.com where you can login using the following details:
<br><br>
Registered Email ID: {{user_obj.email}}
<br>
Password: {{password}}
<br>
<br>
Happy Shipping,
<br>
Team@Pickrr,
<br>
info@pickrr.com